### PR TITLE
update French Translation in code sample

### PR DESCRIPTION
**Pull request by BelRarr**

### CODE REVIEW

**Comment by v-maudel** [comment]
Hello, @BelRarr ,

Thank you for your feedback and suggestion.

Unfortunately, we consider that changes inside code is not fully aligned with our criteria for acceptance

Closing this PR since it does not apply

Thank you.
Kind regards,

Microsoft C&E Localization Team

**Comment by BelRarr** [comment]
We'll, that's sad because IMHO code comments are part of the documentation since their main purpose is to provide meaningful and valuable information, and thus, they have to be in the same language as the rest of the documentation.

Thanks anyway.

Tidjani

Le 4 juin 2018 4:03 PM, Mauricio de los Santos <notifications@github.com> a écrit :

Hello, @BelRarr<https://github.com/BelRarr> ,

Thank you for your feedback and suggestion.

Unfortunately, we consider that changes inside code is not fully aligned with our criteria for acceptance

Closing this PR since it does not apply

Thank you.
Kind regards,

Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
Hi @BelRarr , thank you for your comment, we really appreciate it. For now, our internal processes do not allow to modify source code. Your opinion is valid we will discuss it internally.

Thanks for your time and support.  

Kind regards,  Microsoft C&E Localization Team

**Comment by BelRarr** [comment]
Thanks for taking the time to answer me.

Le 5 juin 2018 5:22 PM, Ramiro Del Greco <notifications@github.com> a écrit :

Hi @BelRarr<https://github.com/BelRarr> , thank you for your comment, we really appreciate it. For now, our internal processes do not allow to modify source code. Your opinion is valid we will discuss it internally.

Thanks for your time and support.

Kind regards, Microsoft C&E Localization Team

**Pull request closed without merging**
